name: 'Release'

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  DENO_DIR: ~/.deno-cache

jobs:
  release:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        deno-version: [1.41.3]

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GH_RUNREAL_TOKEN }}
          pull-request-title-pattern: "chore${scope}: release${component} ${version}"
          release-type: simple
          extra-files: |
            README.md
            src/version.ts